CREATE TABLE "patients" (
  "patient_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" string,
  "first_last" string,
  "middle_name" string,
  "middle_last" string,
  "date_of_birth" date,
  "gender" string,
  "registration_date" date,
  "active" boolean
);

CREATE TABLE "patient_emails" (
  "email_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "email" string,
  "email_type" string
);

CREATE TABLE "patient_phones" (
  "phone_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "phone_number" string,
  "phone_type" string
);

CREATE TABLE "patient_addresses" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "address" string,
  "city" string,
  "state" string
);

CREATE TABLE "patient_emergency_contacts" (
  "contact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "contact_name" string,
  "relationship" string,
  "phone" string
);

CREATE TABLE "patient_documents" (
  "document_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "document_type" string,
  "document_number" string
);

CREATE TABLE "insurance_company" (
  "insurance_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string
);

CREATE TABLE "insurance_contact_info" (
  "contact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "insurance_id" int,
  "contact_type" string,
  "contact_value" string
);

CREATE TABLE "insurance_phones" (
  "phone_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "insurance_id" int,
  "phone_number" string,
  "phone_type" string
);

CREATE TABLE "policy" (
  "policy_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "insurance_id" int,
  "policy_number" string,
  "start_date" date,
  "end_date" date,
  "status" string,
  "coverage_summary" string
);

CREATE TABLE "doctor" (
  "doctor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "internal_code" string,
  "medical_license" string,
  "first_name" string,
  "last_name" string,
  "professional_email" string,
  "hire_date" date,
  "schedule" string
);

CREATE TABLE "doctor_specialties" (
  "specialty_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "specialty_name" string,
  "certification" string
);

CREATE TABLE "doctor_phones" (
  "phone_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "phone_number" string,
  "phone_type" string
);

CREATE TABLE "doctor_addresses" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "practical_direction" string,
  "city" string
);

CREATE TABLE "diagnoses" (
  "diagnosis_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cie_code" string,
  "description" string
);

CREATE TABLE "medications" (
  "medication_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "atc_code" string,
  "business_name" string,
  "active_principle" string,
  "presentation" string
);

CREATE TABLE "procedures" (
  "procedure_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" string,
  "description" string,
  "reference_price" decimal
);

CREATE TABLE "medical_records" (
  "record_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "professional_id" int,
  "main_diagnosis_id" int,
  "date_time_registration" datetime,
  "record_type" string,
  "summary_text" string,
  "structured_summary" json
);

CREATE TABLE "record_medications" (
  "record_medication_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "record_id" int,
  "medication_id" int,
  "dosage" string,
  "frequency" string,
  "duration_days" int
);

CREATE TABLE "record_procedures" (
  "record_procedure_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "record_id" int,
  "procedure_id" int,
  "procedure_date" datetime,
  "notes" string
);

CREATE TABLE "appointment" (
  "appointment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "doctor_id" int,
  "record_id" int,
  "date" date,
  "start_time" time,
  "end_time" time,
  "visit_type" string,
  "status" string,
  "reason" string,
  "room_id" int
);

ALTER TABLE "patient_emails" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "patient_phones" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "patient_addresses" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "patient_emergency_contacts" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "patient_documents" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "insurance_contact_info" ADD FOREIGN KEY ("insurance_id") REFERENCES "insurance_company" ("insurance_id");

ALTER TABLE "insurance_phones" ADD FOREIGN KEY ("insurance_id") REFERENCES "insurance_company" ("insurance_id");

ALTER TABLE "policy" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "policy" ADD FOREIGN KEY ("insurance_id") REFERENCES "insurance_company" ("insurance_id");

ALTER TABLE "doctor_specialties" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "doctor_phones" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "doctor_addresses" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "medical_records" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "medical_records" ADD FOREIGN KEY ("professional_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "medical_records" ADD FOREIGN KEY ("main_diagnosis_id") REFERENCES "diagnoses" ("diagnosis_id");

ALTER TABLE "record_medications" ADD FOREIGN KEY ("record_id") REFERENCES "medical_records" ("record_id");

ALTER TABLE "record_medications" ADD FOREIGN KEY ("medication_id") REFERENCES "medications" ("medication_id");

ALTER TABLE "record_procedures" ADD FOREIGN KEY ("record_id") REFERENCES "medical_records" ("record_id");

ALTER TABLE "record_procedures" ADD FOREIGN KEY ("procedure_id") REFERENCES "procedures" ("procedure_id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("patient_id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("record_id") REFERENCES "medical_records" ("record_id");
